breadcrumb_separator: fa-angle-right
scroll_to_top_display: 1
scroll_to_top_icon: fa-angle-double-up
scroll_to_top_region: footer-to-top-enabled
color_scheme: gray
page_container_border: 0
animations_state: 1
slideout_background_color: 'region--light-typography region--dark-background'
slideout_side: right
slideout_touch_swipe: 0
slideout_blocks_paddings: 0
slideout_region_paddings: 0
header_top_highlighted_layout_container: container
header_top_highlighted_background_color: 'region--dark-typography region--white-background'
header_top_highlighted_animation_effect: fadeIn
header_top_highlighted_blocks_paddings: 0
header_top_highlighted_region_paddings: 0
header_top_layout_container: container
header_top_background_color: 'region--dark-typography region--white-background'
header_top_animation_effect: fadeIn
header_top_blocks_paddings: 0
header_top_region_paddings: 0
header_layout_container: container
header_background_color: 'region--dark-typography region--white-background'
header_blocks_paddings: 0
header_region_paddings: 0
fixed_header: 1
banner_layout_container: container-fluid
banner_background_color: 'region--dark-typography region--white-background'
banner_blocks_paddings: 1
banner_region_paddings: 1
content_top_layout_container: container
content_top_background_color: 'region--dark-typography region--white-background'
content_top_animation_effect: fadeIn
content_top_blocks_paddings: 0
content_top_region_paddings: 0
content_top_highlighted_layout_container: container-fluid
content_top_highlighted_separator: region--no-separator
content_top_highlighted_background_color: 'region--dark-typography region--gray-background'
content_top_highlighted_animation_effect: fadeIn
content_top_highlighted_blocks_paddings: 1
content_top_highlighted_region_paddings: 1
media_background_layout_container: container-fluid
media_background_separator: region--no-separator
media_background_background_color: 'region--dark-typography region--white-background'
media_background_animation_effect: no-animation
media_background_blocks_paddings: 0
media_background_region_paddings: 1
main_content_separator: region--no-separator
main_content_animation_effect: fadeIn
main_content_blocks_paddings: 0
main_content_region_paddings: 0
sidebar_first_animation_effect: fadeInLeft
sidebar_first_blocks_paddings: 0
sidebar_first_region_paddings: 0
sidebar_second_animation_effect: fadeInRight
sidebar_second_blocks_paddings: 0
sidebar_second_region_paddings: 0
content_bottom_layout_container: container-fluid
content_bottom_separator: region--no-separator
content_bottom_background_color: 'region--light-typography region--black-background'
content_bottom_animation_effect: fadeIn
content_bottom_blocks_paddings: 0
content_bottom_region_paddings: 1
featured_top_layout_container: container
featured_top_separator: region--no-separator
featured_top_background_color: 'region--dark-typography region--white-background'
featured_top_animation_effect: fadeInDown
featured_top_blocks_paddings: 0
featured_top_region_paddings: 0
featured_layout_container: container-fluid
featured_separator: region--no-separator
featured_background_color: 'region--dark-typography region--white-background'
featured_animation_effect: fadeInDown
featured_blocks_paddings: 1
featured_region_paddings: 1
featured_bottom_layout_container: container-fluid
featured_bottom_separator: region--no-separator
featured_bottom_background_color: 'region--dark-typography region--gray-background'
featured_bottom_animation_effect: fadeInLeft
featured_bottom_blocks_paddings: 0
featured_bottom_region_paddings: 0
sub_featured_layout_container: container-fluid
sub_featured_separator: region--no-separator
sub_featured_background_color: 'region--dark-typography region--white-background'
sub_featured_animation_effect: fadeIn
sub_featured_blocks_paddings: 1
sub_featured_region_paddings: 1
highlighted_top_layout_container: container
highlighted_top_separator: region--no-separator
highlighted_top_background_color: 'region--dark-typography region--white-background'
highlighted_top_animation_effect: fadeIn
highlighted_top_blocks_paddings: 0
highlighted_top_region_paddings: 0
highlighted_layout_container: container
highlighted_separator: region--no-separator
highlighted_background_color: 'region--dark-typography region--white-background'
highlighted_animation_effect: fadeIn
highlighted_blocks_paddings: 1
highlighted_region_paddings: 1
footer_top_layout_container: container
footer_top_separator: region--no-separator
footer_top_background_color: 'region--light-typography region--dark-background'
footer_top_animation_effect: fadeInUp
footer_top_blocks_paddings: 0
footer_top_region_paddings: 0
footer_layout_container: container
footer_separator: region--no-separator
footer_background_color: 'region--dark-typography region--white-background'
footer_animation_effect: fadeIn
footer_blocks_paddings: 0
footer_region_paddings: 0
footer_bottom_layout_container: container
footer_bottom_separator: region--no-separator
footer_bottom_background_color: 'region--dark-typography region--white-background'
footer_bottom_blocks_paddings: 0
footer_bottom_region_paddings: 0
subfooter_layout_container: container
subfooter_separator: region--separator-border-top
subfooter_background_color: 'region--dark-typography region--white-background'
subfooter_bottom_blocks_paddings: false
subfooter_bottom_region_paddings: false
reading_time: 1
post_progress: 1
layout_mode: wide
headings_font_family: hff-33
headings_wide_spacing: 0
paragraph_font_family: pff-43
sitename_font_family: sff-33
slogan_font_family: slff-33
rs_slideshow_fullscreen_effect: random
rs_slideshow_fullscreen_effect_time: '10'
rs_slideshow_fullscreen_navigation_style: bullets
rs_slideshow_fullscreen_bullets_position: right
rs_slideshow_fullscreen_touch_swipe: 1
transparent_header_state: 1
transparent_header_opacity: '0'
rs_slideshow_fullwidth_effect: random
rs_slideshow_fullwidth_effect_time: '10'
rs_slideshow_fullwidth_initial_height: '650'
rs_slideshow_fullwidth_navigation_style: bullets
rs_slideshow_fullwidth_bullets_position: right
rs_slideshow_fullwidth_touch_swipe: 1
rs_slideshow_boxedwidth_effect: random
rs_slideshow_boxedwidth_effect_time: '10'
rs_slideshow_boxedwidth_initial_height: '650'
rs_slideshow_boxedwidth_navigation_style: bullets
rs_slideshow_boxedwidth_bullets_position: right
rs_slideshow_boxedwidth_touch_swipe: 1
rs_slideshow_internal_effect: fade
rs_slideshow_internal_effect_time: '10'
rs_slideshow_internal_initial_height: '540'
rs_slideshow_internal_navigation_style: bullets
rs_slideshow_internal_banner_bullets_position: left
rs_slideshow_internal_touch_swipe: 1
rs_slideshow_caption_opacity: '45'
in_page_slider_effect: slide
owl_products_autoplay: 1
owl_products_effect_time: '5'
owl_articles_autoplay: 1
owl_articles_effect_time: '5'
owl_testimonials_autoplay: 1
owl_testimonials_effect_time: '5'
owl_related_nodes_autoplay: 0
owl_related_nodes_effect_time: '5'
owl_brands_autoplay: 1
owl_brands_effect_time: '5'
owl_collections_autoplay: 0
owl_collections_effect_time: '5'
parallax_and_video_bg_state: none
parallax_and_video_bg_opacity: '0'
isotope_layout_mode: masonry
isotope_filters_text: All
google_maps_key: AIzaSyDyL-4KyWw_3hp-0jmZLGcJ3zMWkkJ44VI
_core:
  default_config_hash: gsXSOA8a_4BXqy59goXiOz0UhPWuzH4JlYW3FzQCZPc
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
subfooter_blocks_paddings: 0
subfooter_region_paddings: 0
font_title: ''
rs_slideshow_internal_bullets_position: center
video_bg_state: none
video_bg_opacity: ''
bootstrap_remote_type: local
owl_promoted_posts_autoplay: 0
owl_promoted_posts_effect_time: '5'
font_resize: 1
affix_side: 1
share_links: 1
print_button: 1
share_links_print_position: bottom
owl_team_members_autoplay: 0
owl_team_members_effect_time: '5'
inverse_header_state: 1
inverted_header_state: 1
rs_slideshow_background_opacity: '30'
banner_id: banner
content_top_id: content-top
content_top_highlighted_id: content-top-highlighted
main_content_id: main-content
content_bottom_id: content-bottom
featured_top_id: featured-top
featured_id: featured
featured_bottom_id: featured-bottom
sub_featured_id: sub-featured
highlighted_top_id: highlighted-top
highlighted_id: highlighted
footer_top_id: footer-top
footer_id: footer
footer_bottom_id: footer-bottom
subfooter_id: subfooter
in_page_navigation_offset: '74'
