label: 'Media Entity Browser'
display_configuration:
  link_text: 'Select media'
widgets:
  6586703a-6976-4124-8a49-cbb07ceaa3b1:
    settings:
      submit_text: 'Select media'
    label: 'Choose existing media'
  ecb3940b-e53b-4bc5-acb5-930d8780ea2f:
    label: 'Upload new image'
