module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_translation: 0
  contextual: 0
  datetime: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_resmushit: 0
  inline_entity_form: 0
  language: 0
  lazy: 0
  link: 0
  locale: 0
  media: 0
  media_entity_browser: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  search: 0
  shortcut: 0
  superfish: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  menu_link_content: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  corporateplus: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
langcode: de
