alter_tag:
  img: img
  iframe: iframe
skipClass: no-b-lazy
placeholderSrc: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
image_fields:
  paragraph--sas_bild--field_sas_image_ref--default: '1'
  paragraph--sas_media_object--field_sas_image_ref--default: '1'
  node--article--field_image--default: '1'
  node--mt_benefit--field_image--default: '1'
  node--page--field_image--default: '1'
  node--mt_product--field_image--default: '1'
  node--mt_service--field_image--default: '1'
  node--mt_showcase--field_image--default: '1'
  node--mt_slideshow_entry--field_mt_slideshow_image--default: '1'
  node--mt_team_member--field_mt_member_photo--default: '1'
  node--mt_testimonial--field_mt_testimonial_image--default: '1'
  paragraph--sas_bild--field_sas_image_ref--preview: '1'
  node--mt_service--field_image--search_index: '1'
  node--page--field_image--search_index: '1'
  node--mt_product--field_image--search_index: '1'
  paragraph--sas_media_object--field_sas_image_ref--preview: '1'
  user--user--user_picture--default: '1'
  node--mt_slideshow_entry--field_mt_slideshow_image--search_index: '1'
  node--mt_product--field_image--rss: '1'
  node--mt_product--field_image--grid_view: '1'
  node--mt_testimonial--field_mt_testimonial_image--search_index: '1'
  node--article--field_image--search_index: '1'
  node--partner--field_image--default: '1'
  node--partner--field_image--search_index: '1'
  node--mt_team_member--field_mt_member_photo--search_index: '1'
  node--download--field_image--default: '1'
disabled_paths: /rss.xml
_core:
  default_config_hash: h_4N5fL4QosXf3JITfYemQOmapK2xYFlwZGOv371LH8
langcode: de
lazysizes:
  lazyClass: b-lazy
  loadedClass: lazyloaded
  loadingClass: lazyloading
  preloadClass: lazypreload
  errorClass: b-error
  autosizesClass: lazyautosizes
  srcAttr: data-src
  srcsetAttr: data-srcset
  sizesAttr: data-sizes
  minSize: 40
  customMedia: {  }
  init: true
  expFactor: 1.5
  hFac: 0.8
  loadMode: 2
  loadHidden: true
  ricTimeout: 0
  throttleDelay: 125
  plugins: {  }
formatters:
  lazy_image: '0'
  lazy_responsive_image: '0'
preferNative: true
