label: 'Media Entity Browser (Modal)'
display_configuration:
  link_text: 'Select media'
widgets:
  fc729026-c85f-4561-acd5-38d4082b69fb:
    settings:
      submit_text: 'Select media'
    label: 'Choose existing media'
  9769d4e4-1f9c-4313-8b01-fe8cff8aa5a1:
    label: 'Upload new image'
